Fix dependsOn mistyped
A Fatal error is throwed in `details.php` because dependsOn is filled as a string instead an array
```
Fatal error: Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in /var/www/html/detail.php:81 Stack trace: #0 /var/www/html/detail.php(81): implode(', ', 'Segmented netwo...') #1 /var/www/html/report.php(68): printDetail('Test and Verifi...', 'Dynamic depth f...', 'Test network se...', Array, true) #2 {main} thrown in /var/www/html/detail.php on line 81
```

To fix it I just updated the involved yaml file